name: Pixi setup

on:
  push:
    branches: [ windowsos ]
  pull_request:
    branches: [ main ]

jobs:
  default:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Python environment
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Setup Pixi Environment
        uses: prefix-dev/setup-pixi@v0.8.5
        with:
          pixi-version: latest